version: "3.8"

services:
  app:
    build: .
    container_name: fruitables_app
    ports:
      - "3000:3000"
    env_file:
      - .env

  nginx:
    image: nginx:latest
    container_name: fruitables_nginx
    ports:
      - "80:80"
    depends_on:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
